[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mazegen"
version = "1.0.0"
description = "A standalone, reusable maze generator package for the 42 A-Maze-ing project."
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
    { name = "luafranc" },
    { name = "jamsilva" }
]
keywords = ["maze", "generator", "42", "dfs", "algorithms", "pacman"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = []

[tool.setuptools.packages.find]
where = ["."]
include = ["mazegen*"]

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_ignores = true
ignore_missing_imports = true
disallow_untyped_defs = true
check_untyped_defs = true
exclude = [
    "^\\.venv/",
    "^venv/",
    "^\\.testenv/",
    "^build/",
    "^dist/"
]